title: We're not ready. But we never have been.
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.04829743201844394
  brandStrength: 0.4066312219947577
  rhythmicContrast: 0.8619211562909186
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
  lightness: 0.4357153815217316
typography_spectrum: 0.4020311
navigation:
  - id: 7e44c44a-7b6d-4090-8c3c-429c0e6e8e07
    url: 2016-07-24-unprepared.html
    name: un/prepared
    type: content
  - id: www.causeit.org
    url: www.causeit.org
    name: causeit
    type: external
layout_spectrum: 1
name: cybiome
